version: '3'
services:

  db:
    image: mysql/mysql-server:5.7
    container_name: mysql5.7
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: emlog
      MYSQL_USER: emlog
      MYSQL_PASSWORD: emlog
    networks:
      - emlog_network

  php:
    # image: php:8.0.12-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/app/emlog
    working_dir: /app/emlog
    networks:
      - emlog_network
    ports:
      - "9000:9000"
    environment:
      EMLOG_DB_HOST: db:3306
      EMLOG_DB_USER: emlog
      EMLOG_DB_NAME: emlog
      EMLOG_DB_PASSWORD: emlog

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/app/emlog
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - emlog_network
    depends_on:
      - php

networks:
  emlog_network:
    external: true